<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.GtitT4t' shared service.

return $this->privates['.service_locator.GtitT4t'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, array(
    'cvRepository' => array('privates', 'App\\Repository\\CvRepository', 'getCvRepositoryService.php', true),
));
