<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.hkFXrRu' shared service.

return $this->privates['.service_locator.hkFXrRu'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, array(
    'langueRepository' => array('privates', 'App\\Repository\\LangueRepository', 'getLangueRepositoryService.php', true),
));
