<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.opAr.iH' shared service.

return $this->privates['.service_locator.opAr.iH'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, array(
    'langue' => array('privates', '.errored..service_locator.opAr.iH.App\\Entity\\Langue', NULL, 'Cannot autowire service ".service_locator.opAr.iH": it references class "App\\Entity\\Langue" but no such service exists.'),
));
