<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.zBOqTb5' shared service.

return $this->privates['.service_locator.zBOqTb5'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, array(
    'experience' => array('privates', '.errored..service_locator.zBOqTb5.App\\Entity\\Experience', NULL, 'Cannot autowire service ".service_locator.zBOqTb5": it references class "App\\Entity\\Experience" but no such service exists.'),
));
