<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAYmxhA8\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAYmxhA8/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAYmxhA8.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAYmxhA8\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerAYmxhA8\srcApp_KernelDevDebugContainer(array(
    'container.build_hash' => 'AYmxhA8',
    'container.build_id' => 'ec007bec',
    'container.build_time' => 1547079776,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerAYmxhA8');
